/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AgriculturalSuppliesRouteImport } from './routes/agricultural-supplies'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AgriculturalSuppliesRoute = AgriculturalSuppliesRouteImport.update({
  id: '/agricultural-supplies',
  path: '/agricultural-supplies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/agricultural-supplies': typeof AgriculturalSuppliesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/projects': typeof ProjectsRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/agricultural-supplies': typeof AgriculturalSuppliesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/projects': typeof ProjectsRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/agricultural-supplies': typeof AgriculturalSuppliesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/projects': typeof ProjectsRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agricultural-supplies'
    | '/contact'
    | '/faq'
    | '/projects'
    | '/admin/login'
    | '/blog/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/agricultural-supplies'
    | '/contact'
    | '/faq'
    | '/projects'
    | '/admin/login'
    | '/blog/$slug'
    | '/services/$slug'
    | '/blog'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agricultural-supplies'
    | '/contact'
    | '/faq'
    | '/projects'
    | '/admin/login'
    | '/blog/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgriculturalSuppliesRoute: typeof AgriculturalSuppliesRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ProjectsRoute: typeof ProjectsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agricultural-supplies': {
      id: '/agricultural-supplies'
      path: '/agricultural-supplies'
      fullPath: '/agricultural-supplies'
      preLoaderRoute: typeof AgriculturalSuppliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AgriculturalSuppliesRoute: AgriculturalSuppliesRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ProjectsRoute: ProjectsRoute,
  BlogSlugRoute: BlogSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
